// Study Materials Data
const studyMaterials = [
    {
        categoryId: 15,
        categoryName: 'Board Exam Solution',
        class: 10,
        title: 'English 2025 Board Exam Solution',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNybvWIOj8Ufm8%3D',
    },
    {
        categoryId: 23,
        categoryName: 'Board Exam Question Paper',
        class: 10,
        title: 'English 2025 Board Exam Question Paper',
        url: 'https://drive.google.com/file/d/1oOngaHDenJ0xHOse382kRs3NE704U5Kr/view?usp=drivesdk',
    },
    {
        categoryId: 15,
        categoryName: 'Board Exam Solution',
        class: 10,
        title: 'Geography 2025 Board Exam Solution',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNyhfjdjIOj8Ufm8%3D',
    },
    {
        categoryId: 15,
        categoryName: 'Board Exam Solution',
        class: 10,
        title: 'Geography 2024 Board Exam Solution',
        url: 'https://youtu.be/CjyvBCiEFOs?si=crz5g-HcuV32vkFk',
    },
    {
        categoryId: 15,
        categoryName: 'Board Exam Solution',
        class: 10,
        title: 'Algebra 2025 Board Exam Solution',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNybvWIOj8Ufm8%3D',
    },
    {
        categoryId: 15,
        categoryName: 'Board Exam Solution',
        class: 10,
        title: 'Science 2025 Board Exam Solution',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNybvWIOj8Ufm8%3D',
    },
    {
        categoryId: 23,
        categoryName: 'Board Exam Question Paper',
        class: 10,
        title: 'Science 2025 Board Exam Question Paper',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNybvWIOj8Ufm8%3D',
    },
    {
        categoryId: 15,
        categoryName: 'Board Exam Solution',
        class: 10,
        title: 'History 2025 Board Exam Solution',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNybvWIOj8Ufm8%3D',
    },
    {
        categoryId: 15,
        categoryName: 'Board Exam Solution',
        class: 10,
        title: 'Marathi 2025 Board Exam Solution',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNybvWIOj8Ufm8%3D',
    },
    {
        categoryId: 15,
        categoryName: 'Board Exam Solution',
        class: 10,
        title: 'Hindi 2025 Board Exam Solution',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNybvWIOj8Ufm8%3D',
    },
    {
        categoryId: 15,
        categoryName: 'Board Exam Solution',
        class: 12,
        title: 'Physics 2025 Board Exam Solution',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNybvWIOj8Ufm8%3D',
    },
    {
        categoryId: 23,
        categoryName: 'Board Exam Question Paper',
        class: 12,
        title: 'Physics 2025 Board Exam Question Paper',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNybvWIOj8Ufm8%3D',
    },
    {
        categoryId: 15,
        categoryName: 'Board Exam Solution',
        class: 12,
        title: 'Chemistry 2025 Board Exam Solution',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNybvWIOj8Ufm8%3D',
    },
    {
        categoryId: 15,
        categoryName: 'Board Exam Solution',
        class: 12,
        title: 'Mathematics 2025 Board Exam Solution',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNybvWIOj8Ufm8%3D',
    },
    {
        categoryId: 23,
        categoryName: 'Board Exam Question Paper',
        class: 12,
        title: 'Mathematics 2025 Board Exam Question Paper',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNybvWIOj8Ufm8%3D',
    },
    {
        categoryId: 15,
        categoryName: 'Board Exam Solution',
        class: 12,
        title: 'Biology 2025 Board Exam Solution',
        url: 'https://app.ylearn.in/eK3sAuUHnshFEr9VXf6Qb2LFJdfGzXNybvWIOj8Ufm8%3D',
    },
];
